# Configuração Prometheus para ChatBOT Discord

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'chatbot-monitor'

# Regras de alerta (opcional)
rule_files:
  # - "alerts.yml"

# Configuração de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - Métricas do servidor
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'vps-chatbot'

  # cAdvisor - Métricas dos containers
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'docker-containers'

  # Docker daemon metrics (se habilitado)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'container_.*'
        action: keep
