name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Check and Update Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pip-audit
      run: pip install pip-audit

    - name: Security audit
      run: |
        pip-audit --desc --fix --dry-run > security-report.txt || true

    - name: Check for outdated packages
      run: |
        pip list --outdated > outdated-packages.txt || true

    - name: Create issue if vulnerabilities found
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('security-report.txt', 'utf8');

          if (report.includes('vulnerabilities found')) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security: Vulnerabilities found in dependencies',
              body: '## Security Audit Report\n\n```\n' + report + '\n```\n\nPlease review and update affected packages.',
              labels: ['security', 'dependencies']
            });
          }
